### ISSUE TITLE
Remove `android-os.lisp`

### ISSUE THREAD

**Issue by aadcg** [bohonghuang/sbcl-termux-build#2]
Could you explain me why the following file was removed? It is possible to read `/proc/cpuinfo` from non-rooted Android devices. Thanks.

https://github.com/bohonghuang/sbcl-termux-build/blob/7091e4dc65912de03247bd42fccfe2efd620adb7/build.sh#L27

**Comment by bohonghuang** [comment]
> Could you explain me why the following file was removed?

If we build SBCL with this file included, SBCL will warn of the undefined symbol `software_version` at every startup. On the other hand, the feature `:LINUX` is present on Android, so the file `linux-os` is also included, which leads to the functions in `android-os` is actually redefined by `linux-os`.

> It is possible to read `/proc/cpuinfo` from non-rooted Android devices.

That seems possible, at least on my Android 10 device.

**Comment by aadcg** [comment]
> If we build SBCL with this file included, SBCL will warn of the undefined symbol software_version at every startup. On the other hand, the feature :LINUX is present on Android, so the file linux-os is also included, which leads to the functions in android-os is actually redefined by linux-os.

Clear. The issue is that `(with-open-file (f "/proc/sys/kernel/osrelease") (read-line f))` doesn't work in Android. I know to how to patch `android-os.lisp` so that `software-version` will be defined properly for Android. I'll share it with you later.

Could you please explain your other patch?

```sed -i "s/#ifdef SVR4/#if defined(SVR4) || defined(LISP_FEATURE_ANDROID)/" src/runtime/run-program.c```

Thanks.

**Comment by aadcg** [comment]
I think I understood why you patched `run-program.c`.

```log
run-program.c:150:20: warning: call to undeclared function 'getdtablesize'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            last = getdtablesize()-1;
                   ^
1 warning generated.
```

**Comment by aadcg** [comment]
[You can see the patches I've applied to the SBCL sources](https://github.com/termux/termux-packages/pull/14435). Notice that they allow for a proper `software-version` definition.
