### ISSUE TITLE
Clarify build procedure in Readme

### ISSUE THREAD

**Issue by akater** [bohonghuang/sbcl-termux-build#3]
The current

> Reference

> https://bugs.launchpad.net/sbcl/+bug/1956852 for building SBCL using ECL on Android with Termux

reads like the linked bug entry contains correct build instructions.  It does not; I ended up submitting a duplicate of it.  Consider clarifying what works and what doesn't.  ECL 21.2.1-2 will not compile 2.2.0, 2.3.3 and probably other releases.

**Comment by bohonghuang** [comment]
The `build.sh` script already contains the complete build process and should be ready to use out of the box. 

> ECL 21.2.1-2 will not compile 2.2.0, 2.3.3 and probably other releases.

Bootstrapping SBCL using SBCL should be preferred, and if you want to use ECL, you need to clone the latest ECL Git branch, as is done in the `build.sh` file.

**Comment by akater** [comment]
Great.  It's probably better to direct visitors to `build.sh` then, rather than to that bug entry alone.
